pipeline {
    agent {
        label 'docker-maven-trivy'
    }
    
    environment {
        SONAR_IP = ''
    }
    stages{
        stage("checkout"){
            steps{
                checkout scm
            }
        }

        stage("Trivey FS Scan"){
            steps{
                sh 'trivy fs --exit-code 1 --severity HIGH,CRITICAL .'
            }
        }

        stage("Build and Sonar"){
            withCredentials([string(credentialsId: 'sonarqube-token', variable: 'SONAR_TOKEN')]) {
                sh 'mvn clean verify sonar:sonar \
                -Dsonar.projectKey=devsecops-demo \
                -Dsonar.host.url="http://${SONAR_IP}:9000" \
                -Dsonar.token="${SONAR_TOKEN}" \
                -Dsonar.qualityGate.wait=true'
            }
        }
    }
}