pipeline {
    agent {
        label 'docker-maven-trivy'
    }
    
    stages{
        stage("checkout"){
            steps{
                checkout scm
            }
        }
        stage("Trivey FS Scan"){
            steps{
                sh 'trivy fs --exit-code 1 --severity HIGH,CRITICAL .'
            }
        }
    }
}